name: Reuseable Unit Test

on:
  workflow_call:
  pull_request:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout and setup
        uses: actions/checkout@v3

      - name: Checkout and setup
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        name: Caching package
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install depencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn

      - name: Prepare environment for testing
        run: |
          cp .env.example .env

      - name: Run unit test
        run: |
          yarn test
